### ISSUE TITLE
New mappings needed between ICES MATRX terms and BODC S12 biological entity subcomponent terms (BODCNVS-1060)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/ICES-NVS_mappings#1]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/NORTHS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/NORTHS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

ICES MATRX term | description | NVS vocab | NVS vocab code | NVS url | mapping | ICES url
-- | -- | -- | -- | -- | -- | --
  |   |   | Subcomponent |   |   |  
GO | gonads | New mapping | S12 | S1236 | http://vocab.nerc.ac.uk/collection/S12/current/S1236/ | skos:related | http://vocab.ices.dk/services/rdf/collection/MATRX/GO
GI | gill | New mapping | S12 | S1233 | http://vocab.nerc.ac.uk/collection/S12/current/S1233/ | skos:related | http://vocab.ices.dk/services/rdf/collection/MATRX/GI
BA | baleen | New term and mapping | S12 |   |   | skos:related | http://vocab.ices.dk/services/rdf/collection/MATRX/BA
TM | muscle tissue | New mapping | S12 | S1218 | http://vocab.nerc.ac.uk/collection/S12/current/S1218/ | skos:related | http://vocab.ices.dk/services/rdf/collection/MATRX/TM
EH | egg yolk and albumen homogenate | Exists already | S12 | S1255 | http://vocab.nerc.ac.uk/collection/S12/current/S1255/ | skos:related | http://vocab.ices.dk/services/rdf/collection/MATRX/EH
BL | blood | New mapping | S12 | S1230 | http://vocab.nerc.ac.uk/collection/S12/current/S1230/ | skos:related | http://vocab.ices.dk/services/rdf/collection/MATRX/BL
MU&EP | muscle tissues and skin | New mapping | S12 | S1258 | http://vocab.nerc.ac.uk/collection/S12/current/S1258/ | skos:related | http://vocab.ices.dk/services/rdf/collection/MATRX/MU&EP

</body>

</html>

**Comment by danibodc** [comment]
These mappings have now been created.
