### ISSUE TITLE
New mappings needed between ICES MATRX terms and BODC S11 biological entity lifestage terms (BODCNVS-1060)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/ICES-NVS_mappings#2]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/NORTHS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/NORTHS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

ICES MATRX term | description | NVS vocab | NVS vocab code | NVS url | mapping | ICES url
-- | -- | -- | -- | -- | -- | --
RO | fish eggs | New mapping | S11 | S1122 | http://vocab.nerc.ac.uk/collection/S11/current/S1122/ | skos:related | http://vocab.ices.dk/services/rdf/collection/MATRX/RO
EH | egg yolk and albumen homogenate | New mapping | S11 | S1122 | http://vocab.nerc.ac.uk/collection/S11/current/S1122/ | skos:related | http://vocab.ices.dk/services/rdf/collection/MATRX/EH

</body>

</html>

**Comment by danibodc** [comment]
These mappings have now been created.
